// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyProductAttribute("Chauffeur.ExternalPackages")>]
[<assembly: AssemblyTitleAttribute("Chauffeur External Package tools")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: AssemblyMetadataAttribute("githash","d7eb45")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "Chauffeur.ExternalPackages"
    let [<Literal>] AssemblyTitle = "Chauffeur External Package tools"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] ComVisible = false
    let [<Literal>] AssemblyMetadata_githash = "d7eb45"
