// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Chauffeur.ExternalPackages.UmbracoRepositoryWrapper")]
[assembly: AssemblyTitleAttribute("Chauffeur External Package tools - wrapper for package feed")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyMetadataAttribute("githash","d7eb45")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Chauffeur.ExternalPackages.UmbracoRepositoryWrapper";
        internal const System.String AssemblyTitle = "Chauffeur External Package tools - wrapper for package feed";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
        internal const System.String AssemblyInformationalVersion = "1.0.0";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyMetadata_githash = "d7eb45";
    }
}
